spring:
  application:
    name: nexusvoice-backend
  threads:
    virtual:
      enabled: true
  # 引入本地配置文件（包含敏感信息）
  profiles:
    include: local
  # 数据源配置 - 使用Druid连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,192.168.1.0/24
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        # 禁用HTML页面上的"Reset All"功能
        reset-enable: false
        # 登录名和密码在 application-local.yml 中配置
        # login-username: 请在 application-local.yml 中配置
        # login-password: 请在 application-local.yml 中配置

# MyBatis-Plus配置
mybatis-plus:
  # 配置扫描通用枚举，支持统一的枚举处理
  type-enums-package: com.nexusvoice.domain.user.constant
  configuration:
    # 是否开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 全局默认主键类型
      id-type: ASSIGN_ID
      # 逻辑删除配置
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      # 字段验证策略
      insert-strategy: NOT_EMPTY
      update-strategy: NOT_EMPTY
      where-strategy: NOT_EMPTY

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,druid

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.nexusvoice: DEBUG
    # MyBatis日志
    com.nexusvoice.mapper: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

# LangChain4j配置 - 敏感信息在 application-local.yml 中配置
langchain4j:
  open-ai:
    # API密钥在 application-local.yml 中配置
    api-key: ${OPENAI_API_KEY:please-set-in-application-local-yml}
    base-url: ${OPENAI_BASE_URL:https://api.openai.com/v1}
    chat-model:
      model-name: ${OPENAI_CHAT_MODEL:gpt-4o-mini}
      temperature: ${OPENAI_TEMPERATURE:0.7}
      max-tokens: ${OPENAI_MAX_TOKENS:2000}
    embedding-model:
      model-name: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
  # PGVector配置
  pgvector:
    host: ${PGVECTOR_HOST:localhost}
    port: ${PGVECTOR_PORT:5432}
    database: ${PGVECTOR_DATABASE:nexusvoice_dev}
    user: ${PGVECTOR_USER:please-set-in-application-local-yml}
    password: ${PGVECTOR_PASSWORD:please-set-in-application-local-yml}
    dimension: ${PGVECTOR_DIMENSION:1536}
    table: ${PGVECTOR_TABLE:embeddings}
    index-list-size: ${PGVECTOR_INDEX_LIST_SIZE:1000}

# JWT配置 - 敏感信息在 application-local.yml 中配置
jwt:
  # JWT密钥（生产环境请使用环境变量）
  secret: ${JWT_SECRET:please-set-in-application-local-yml}
  # 访问令牌过期时间（毫秒）- 24小时
  expiration: ${JWT_EXPIRATION:86400000}
  # 刷新令牌过期时间（毫秒）- 7天
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  # JWT签发者
  issuer: ${JWT_ISSUER:nexusvoice}

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    # PostgreSQL数据库连接信息在 application-local.yml 中配置
    # url: 请在 application-local.yml 中配置
    # username: 请在 application-local.yml 中配置
    # password: 请在 application-local.yml 中配置
    driver-class-name: org.postgresql.Driver

# MyBatis-Plus开发环境配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  level:
    root: INFO
    com.nexusvoice: DEBUG
    com.nexusvoice.mapper: DEBUG

---
# 测试环境配置
spring:
  config:
    activate:
      on-profile: test
  datasource:
    # 测试环境PostgreSQL数据库连接信息（可根据需要配置）
    url: jdbc:postgresql://localhost:5432/nexusvoice_test?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${TEST_DB_USERNAME:postgres}
    password: ${TEST_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

logging:
  level:
    root: INFO
    com.nexusvoice: DEBUG

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/nexusvoice_prod?useUnicode=true&characterEncoding=utf8&useSSL=true}
    username: ${DB_USERNAME:nexusvoice}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
    druid:
      # 生产环境连接池配置
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      # 关闭监控页面
      stat-view-servlet:
        enabled: false
      web-stat-filter:
        enabled: false

# MyBatis-Plus生产环境配置
mybatis-plus:
  configuration:
    # 生产环境关闭SQL日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml

server:
  forward-headers-strategy: framework

logging:
  level:
    root: WARN
    com.nexusvoice: INFO
