version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: nexusvoice-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nexusvoice_dev
      MYSQL_USER: nexusvoice
      MYSQL_PASSWORD: nexusvoice123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: nexusvoice-phpmyadmin-dev
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mysql
    restart: unless-stopped

volumes:
  mysql_data:
